### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mattbrailsford** [vendrcontrib/vendr-payment-provider-yourpay#1]
Just to note a few things to resolve in this

- [x] Remove the init.ps1 and init.cmd files
- [x] Update `Build.Prepare.targets` with Flurl DLL dependencies (See https://github.com/vendrhub/vendr-payment-provider-paypal/blob/dev/build/Build.Prepare.targets#L13-L14)
- [x] Update NuSpec file to include Flurl dependencies (See https://github.com/vendrhub/vendr-payment-provider-paypal/blob/dev/build/NuSpecs/Vendr.PaymentProviders.PayPal.nuspec#L19-L20)
- [x] Update NuSpec files Author, Owners and Copyright as they won't be `Outfield Digital`
- [x] Check `FetchPaymentStatus` on order
- [x] Test installing packages both by nuget and umbraco package file
